extends:
  - airbnb
  # - eslint:recommended
  # - plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import
rules:
  import/no-extraneous-dependencies: 0
  react/jsx-filename-extension: 0
  jsx-a11y/label-has-for:
    - 2
    - components:
        - Label
      required:
        every:
          - id
          # - nesting
      allowChildren: false
